export const deck = [
  { displayValue: 'A', value: 1, suit: 'spade', key: 'aSpade', faceUp: false},
  { displayValue: '2', value: 2, suit: 'spade', key: '2Spade', faceUp: false},
  { displayValue: '3', value: 3, suit: 'spade', key: '3Spade', faceUp: false},
  { displayValue: '4', value: 4, suit: 'spade', key: '4Spade', faceUp: false},
  { displayValue: '5', value: 5, suit: 'spade', key: '5Spade', faceUp: false},
  { displayValue: '6', value: 6, suit: 'spade', key: '6Spade', faceUp: false},
  { displayValue: '7', value: 7, suit: 'spade', key: '7Spade', faceUp: false},
  { displayValue: '8', value: 8, suit: 'spade', key: '8Spade', faceUp: false},
  { displayValue: '9', value: 9, suit: 'spade', key: '9Spade', faceUp: false},
  { displayValue: '10', value: 10, suit: 'spade', key: '10Spade', faceUp: false},
  { displayValue: 'J', value: 11, suit: 'spade', key: 'jSpade', faceUp: false},
  { displayValue: 'Q', value: 12, suit: 'spade', key: 'qSpade', faceUp: false},
  { displayValue: 'K', value: 13, suit: 'spade', key: 'kSpade', faceUp: false},

  { displayValue: 'A', value: 1, suit: 'club', key: 'aClub', faceUp: false},
  { displayValue: '2', value: 2, suit: 'club', key: '2Club', faceUp: false},
  { displayValue: '3', value: 3, suit: 'club', key: '3Club', faceUp: false},
  { displayValue: '4', value: 4, suit: 'club', key: '4Club', faceUp: false},
  { displayValue: '5', value: 5, suit: 'club', key: '5Club', faceUp: false},
  { displayValue: '6', value: 6, suit: 'club', key: '6Club', faceUp: false},
  { displayValue: '7', value: 7, suit: 'club', key: '7Club', faceUp: false},
  { displayValue: '8', value: 8, suit: 'club', key: '8Club', faceUp: false},
  { displayValue: '9', value: 9, suit: 'club', key: '9Club', faceUp: false},
  { displayValue: '10', value: 10, suit: 'club', key: '10Club', faceUp: false},
  { displayValue: 'J', value: 11, suit: 'club', key: 'jClub', faceUp: false},
  { displayValue: 'Q', value: 12, suit: 'club', key: 'qClub', faceUp: false},
  { displayValue: 'K', value: 13, suit: 'club', key: 'kClub', faceUp: false},

  { displayValue: 'A', value: 1, suit: 'diamond', key: 'aDiamond', faceUp: false},
  { displayValue: '2', value: 2, suit: 'diamond', key: '2Diamond', faceUp: false},
  { displayValue: '3', value: 3, suit: 'diamond', key: '3Diamond', faceUp: false},
  { displayValue: '4', value: 4, suit: 'diamond', key: '4Diamond', faceUp: false},
  { displayValue: '5', value: 5, suit: 'diamond', key: '5Diamond', faceUp: false},
  { displayValue: '6', value: 6, suit: 'diamond', key: '6Diamond', faceUp: false},
  { displayValue: '7', value: 7, suit: 'diamond', key: '7Diamond', faceUp: false},
  { displayValue: '8', value: 8, suit: 'diamond', key: '8Diamond', faceUp: false},
  { displayValue: '9', value: 9, suit: 'diamond', key: '9Diamond', faceUp: false},
  { displayValue: '10', value: 10, suit: 'diamond', key: '10Diamond', faceUp: false},
  { displayValue: 'J', value: 11, suit: 'diamond', key: 'jDiamond', faceUp: false},
  { displayValue: 'Q', value: 12, suit: 'diamond', key: 'qDiamond', faceUp: false},
  { displayValue: 'K', value: 13, suit: 'diamond', key: 'kDiamond', faceUp: false},

  { displayValue: 'A', value: 1, suit: 'heart', key: 'aHeart', faceUp: false},
  { displayValue: '2', value: 2, suit: 'heart', key: '2Heart', faceUp: false},
  { displayValue: '3', value: 3, suit: 'heart', key: '3Heart', faceUp: false},
  { displayValue: '4', value: 4, suit: 'heart', key: '4Heart', faceUp: false},
  { displayValue: '5', value: 5, suit: 'heart', key: '5Heart', faceUp: false},
  { displayValue: '6', value: 6, suit: 'heart', key: '6Heart', faceUp: false},
  { displayValue: '7', value: 7, suit: 'heart', key: '7Heart', faceUp: false},
  { displayValue: '8', value: 8, suit: 'heart', key: '8Heart', faceUp: false},
  { displayValue: '9', value: 9, suit: 'heart', key: '9Heart', faceUp: false},
  { displayValue: '10', value: 10, suit: 'heart', key: '10Heart', faceUp: false},
  { displayValue: 'J', value: 11, suit: 'heart', key: 'jHeart', faceUp: false},
  { displayValue: 'Q', value: 12, suit: 'heart', key: 'qHeart', faceUp: false},
  { displayValue: 'K', value: 13, suit: 'heart', key: 'kHeart', faceUp: false},
];
