export const deck = [
  { value: 'A', suit: 'spade', key: 'aSpade', faceUp: false},
  { value: '2', suit: 'spade', key: '2Spade', faceUp: false},
  { value: '3', suit: 'spade', key: '3Spade', faceUp: false},
  { value: '4', suit: 'spade', key: '4Spade', faceUp: false},
  { value: '5', suit: 'spade', key: '5Spade', faceUp: false},
  { value: '6', suit: 'spade', key: '6Spade', faceUp: false},
  { value: '7', suit: 'spade', key: '7Spade', faceUp: false},
  { value: '8', suit: 'spade', key: '8Spade', faceUp: false},
  { value: '9', suit: 'spade', key: '9Spade', faceUp: false},
  { value: '10', suit: 'spade', key: '10Spade', faceUp: false},
  { value: 'J', suit: 'spade', key: 'jSpade', faceUp: false},
  { value: 'Q', suit: 'spade', key: 'qSpade', faceUp: false},
  { value: 'K', suit: 'spade', key: 'kSpade', faceUp: false},

  { value: 'A', suit: 'club', key: 'aClub', faceUp: false},
  { value: '2', suit: 'club', key: '2Club', faceUp: false},
  { value: '3', suit: 'club', key: '3Club', faceUp: false},
  { value: '4', suit: 'club', key: '4Club', faceUp: false},
  { value: '5', suit: 'club', key: '5Club', faceUp: false},
  { value: '6', suit: 'club', key: '6Club', faceUp: false},
  { value: '7', suit: 'club', key: '7Club', faceUp: false},
  { value: '8', suit: 'club', key: '8Club', faceUp: false},
  { value: '9', suit: 'club', key: '9Club', faceUp: false},
  { value: '10', suit: 'club', key: '10Club', faceUp: false},
  { value: 'J', suit: 'club', key: 'jClub', faceUp: false},
  { value: 'Q', suit: 'club', key: 'qClub', faceUp: false},
  { value: 'K', suit: 'club', key: 'kClub', faceUp: false},

  { value: 'A', suit: 'diamond', key: 'aDiamond', faceUp: false},
  { value: '2', suit: 'diamond', key: '2Diamond', faceUp: false},
  { value: '3', suit: 'diamond', key: '3Diamond', faceUp: false},
  { value: '4', suit: 'diamond', key: '4Diamond', faceUp: false},
  { value: '5', suit: 'diamond', key: '5Diamond', faceUp: false},
  { value: '6', suit: 'diamond', key: '6Diamond', faceUp: false},
  { value: '7', suit: 'diamond', key: '7Diamond', faceUp: false},
  { value: '8', suit: 'diamond', key: '8Diamond', faceUp: false},
  { value: '9', suit: 'diamond', key: '9Diamond', faceUp: false},
  { value: '10', suit: 'diamond', key: '10Diamond', faceUp: false},
  { value: 'J', suit: 'diamond', key: 'jDiamond', faceUp: false},
  { value: 'Q', suit: 'diamond', key: 'qDiamond', faceUp: false},
  { value: 'K', suit: 'diamond', key: 'kDiamond', faceUp: false},

  { value: 'A', suit: 'heart', key: 'aHeart', faceUp: false},
  { value: '2', suit: 'heart', key: '2Heart', faceUp: false},
  { value: '3', suit: 'heart', key: '3Heart', faceUp: false},
  { value: '4', suit: 'heart', key: '4Heart', faceUp: false},
  { value: '5', suit: 'heart', key: '5Heart', faceUp: false},
  { value: '6', suit: 'heart', key: '6Heart', faceUp: false},
  { value: '7', suit: 'heart', key: '7Heart', faceUp: false},
  { value: '8', suit: 'heart', key: '8Heart', faceUp: false},
  { value: '9', suit: 'heart', key: '9Heart', faceUp: false},
  { value: '10', suit: 'heart', key: '10Heart', faceUp: false},
  { value: 'J', suit: 'heart', key: 'jHeart', faceUp: false},
  { value: 'Q', suit: 'heart', key: 'qHeart', faceUp: false},
  { value: 'K', suit: 'heart', key: 'kHeart', faceUp: false}
];
