export const deck = [
  { value: 'A', suit: 'spade', visible: false},
  { value: '2', suit: 'spade', visible: false},
  { value: '3', suit: 'spade', visible: false},
  { value: '4', suit: 'spade', visible: false},
  { value: '5', suit: 'spade', visible: false},
  { value: '6', suit: 'spade', visible: false},
  { value: '7', suit: 'spade', visible: false},
  { value: '8', suit: 'spade', visible: false},
  { value: '9', suit: 'spade', visible: false},
  { value: '10', suit: 'spade', visible: false},
  { value: 'J', suit: 'spade', visible: false},
  { value: 'Q', suit: 'spade', visible: false},
  { value: 'K', suit: 'spade', visible: false},

  { value: 'A', suit: 'club', visible: false},
  { value: '2', suit: 'club', visible: false},
  { value: '3', suit: 'club', visible: false},
  { value: '4', suit: 'club', visible: false},
  { value: '5', suit: 'club', visible: false},
  { value: '6', suit: 'club', visible: false},
  { value: '7', suit: 'club', visible: false},
  { value: '8', suit: 'club', visible: false},
  { value: '9', suit: 'club', visible: false},
  { value: '10', suit: 'club', visible: false},
  { value: 'J', suit: 'club', visible: false},
  { value: 'Q', suit: 'club', visible: false},
  { value: 'K', suit: 'club', visible: false},

  { value: 'A', suit: 'diamond', visible: false},
  { value: '2', suit: 'diamond', visible: false},
  { value: '3', suit: 'diamond', visible: false},
  { value: '4', suit: 'diamond', visible: false},
  { value: '5', suit: 'diamond', visible: false},
  { value: '6', suit: 'diamond', visible: false},
  { value: '7', suit: 'diamond', visible: false},
  { value: '8', suit: 'diamond', visible: false},
  { value: '9', suit: 'diamond', visible: false},
  { value: '10', suit: 'diamond', visible: false},
  { value: 'J', suit: 'diamond', visible: false},
  { value: 'Q', suit: 'diamond', visible: false},
  { value: 'K', suit: 'diamond', visible: false},

  { value: 'A', suit: 'heart', visible: false},
  { value: '2', suit: 'heart', visible: false},
  { value: '3', suit: 'heart', visible: false},
  { value: '4', suit: 'heart', visible: false},
  { value: '5', suit: 'heart', visible: false},
  { value: '6', suit: 'heart', visible: false},
  { value: '7', suit: 'heart', visible: false},
  { value: '8', suit: 'heart', visible: false},
  { value: '9', suit: 'heart', visible: false},
  { value: '10', suit: 'heart', visible: false},
  { value: 'J', suit: 'heart', visible: false},
  { value: 'Q', suit: 'heart', visible: false},
  { value: 'K', suit: 'heart', visible: false}
];
